version: '3.9'
services:
  app:
    container_name: flash-webapi
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    # command: CompileDaemon --build="make go-build" --directory=./app --command="make run"
    depends_on:
      - postgresdb
    tty: true
    networks:
      - net1

  postgresdb:
    image: postgres:latest
    container_name: flash-pg
    restart: always 
    hostname: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - net1

  postgresdb_test:
    image: postgres:latest
    container_name: flash-pg_test
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST}
    ports:
      - '4568:5432'
    volumes:
      - ./pg_data_test:/var/lib/postgresql/data
    networks:
      - net1

volumes:
  pg_data: 
  pg_data_test:

# Networks to be created to facilitate communication between containers
networks:
  net1:
    driver: bridge
