basePath: /v1
definitions:
  Error:
    properties:
      error:
        example: message
        type: string
    type: object
  ListPools:
    description: Request list of trading pools
    properties:
      pools:
        description: list of trade pools
        items:
          $ref: '#/definitions/entities.TradePool'
        type: array
    type: object
  RequestPairs:
    description: Request for searching trade pair
    properties:
      protocol:
        allOf:
        - $ref: '#/definitions/entities.SwapProtocol'
        description: trade protocol
      tokenPair:
        allOf:
        - $ref: '#/definitions/entities.TokenPair'
        description: pair of tokens
    type: object
  entities.SwapProtocol:
    properties:
      factoryAddress:
        type: string
      protocolName:
        type: string
      swapRouter:
        type: string
    type: object
  entities.Token:
    properties:
      address:
        type: string
      name:
        type: string
      wei:
        type: integer
    type: object
  entities.TokenPair:
    properties:
      token0:
        $ref: '#/definitions/entities.Token'
      token1:
        $ref: '#/definitions/entities.Token'
    type: object
  entities.TradePair:
    properties:
      pool0:
        $ref: '#/definitions/entities.TradePool'
      pool1:
        $ref: '#/definitions/entities.TradePool'
    type: object
  entities.TradePool:
    properties:
      address:
        type: string
      pair:
        $ref: '#/definitions/entities.TokenPair'
      tradeProvider:
        $ref: '#/definitions/entities.SwapProtocol'
    type: object
info:
  contact: {}
  description: interacting with smart contract, collecting tokens, perform trade
  license:
    name: MIT
  title: Flash Loan Arbitrage bot
  version: "1.0"
paths:
  /contract/tokens:
    get:
      consumes:
      - application/json
      description: Request token list
      operationId: getTokens
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Token'
            type: array
        "507":
          description: Insufficient Storage
          schema:
            $ref: '#/definitions/Error'
      summary: Get Tokens
      tags:
      - Contract
      - tokens
    post:
      consumes:
      - application/json
      description: Add list of tokens
      operationId: addTokens
      parameters:
      - description: Add tokens
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/entities.Token'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Token'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
      summary: Add Tokens
      tags:
      - Contract
      - tokens
  /provider/pairs:
    get:
      consumes:
      - application/json
      description: Get list of pairs
      operationId: getPairs
      parameters:
      - description: Get pairs
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/RequestPairs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.TradePair'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
      summary: Get Pairs
      tags:
      - Provider
      - pairs
    post:
      consumes:
      - application/json
      description: Add list of pairs
      operationId: addPairs
      parameters:
      - description: Add pairs
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/entities.TradePair'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.TradePair'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
      summary: Add Pairs
      tags:
      - Provider
      - pairs
  /storage/pools:
    get:
      consumes:
      - application/json
      description: Get list of pools
      operationId: getPools
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ListPools'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
      summary: Get Pools
      tags:
      - Storage
      - pools
    post:
      consumes:
      - application/json
      description: Add list of pools
      operationId: addPools
      parameters:
      - description: Add pools
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/entities.TradePool'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.TradePool'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        "507":
          description: Insufficient Storage
          schema:
            $ref: '#/definitions/Error'
      summary: Add Pools
      tags:
      - Storage
      - pools
swagger: "2.0"
